name: dart_worker
version: 0.0.1
author: Grant Hutchinson<h.g.utchinson@gmail.com>
description: http work server ready to read get/post requests, utilizing a basic mongodb cache.
homepage: https://github.com/hutchgrant/dart-worker
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: https://github.com/hutchgrant/dart-worker
dev_dependencies:
  mongo_dart: any
  unittest: any
